name: Fabric CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Project"
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: "Run Fabric Tests"
      uses: Geometrically/fabric-test-runner@v1
      with:
        minecraftVersion: 1.18.2
    
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: Builds
        path: build/libs
